Forward LDFLAGS for ICU build
- Propagate linker flags for ICU build
- Fix build issue with enabled sanitizer:

```
/usr/bin/ld: ../../lib/libicuuc.a(putil.ao): undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
```